# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tax.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(910, 776)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_train = QtWidgets.QWidget(Form)
        self.widget_train.setMinimumSize(QtCore.QSize(700, 0))
        self.widget_train.setObjectName("widget_train")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_train)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_train)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_train)
        self.widget.setMinimumSize(QtCore.QSize(130, 0))
        self.widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_loadSample = QtWidgets.QPushButton(self.widget)
        self.pushButton_loadSample.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_loadSample.setObjectName("pushButton_loadSample")
        self.verticalLayout_4.addWidget(self.pushButton_loadSample)
        self.pushButton_extractFeature = QtWidgets.QPushButton(self.widget)
        self.pushButton_extractFeature.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_extractFeature.setObjectName("pushButton_extractFeature")
        self.verticalLayout_4.addWidget(self.pushButton_extractFeature)
        self.pushButton_startTrain = QtWidgets.QPushButton(self.widget)
        self.pushButton_startTrain.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_startTrain.setObjectName("pushButton_startTrain")
        self.verticalLayout_4.addWidget(self.pushButton_startTrain)
        spacerItem = QtWidgets.QSpacerItem(20, 223, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_train)
        self.widget_2.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_trainSamples = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget_trainSamples.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWidget_trainSamples.setObjectName("tableWidget_trainSamples")
        self.tableWidget_trainSamples.setColumnCount(2)
        self.tableWidget_trainSamples.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_trainSamples.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_trainSamples.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tableWidget_trainSamples)
        self.tableWidget_trainFeature = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget_trainFeature.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWidget_trainFeature.setObjectName("tableWidget_trainFeature")
        self.tableWidget_trainFeature.setColumnCount(2)
        self.tableWidget_trainFeature.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_trainFeature.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_trainFeature.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tableWidget_trainFeature)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_train)
        self.widget_3.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_caseNum = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_caseNum.setReadOnly(True)
        self.lineEdit_caseNum.setObjectName("lineEdit_caseNum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_caseNum)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_corpusSize = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_corpusSize.setReadOnly(True)
        self.lineEdit_corpusSize.setObjectName("lineEdit_corpusSize")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_corpusSize)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_lawNum = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_lawNum.setReadOnly(True)
        self.lineEdit_lawNum.setObjectName("lineEdit_lawNum")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_lawNum)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_featureDim = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_featureDim.setReadOnly(True)
        self.lineEdit_featureDim.setObjectName("lineEdit_featureDim")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_featureDim)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_10.addWidget(self.widget_train)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_10.addWidget(self.progressBar)
        self.widget_test = QtWidgets.QWidget(Form)
        self.widget_test.setObjectName("widget_test")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_test)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.widget_test)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_test)
        self.widget_4.setMinimumSize(QtCore.QSize(130, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_loadTestCase = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_loadTestCase.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_loadTestCase.setObjectName("pushButton_loadTestCase")
        self.verticalLayout_8.addWidget(self.pushButton_loadTestCase)
        self.pushButton_startTest = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_startTest.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_startTest.setObjectName("pushButton_startTest")
        self.verticalLayout_8.addWidget(self.pushButton_startTest)
        spacerItem2 = QtWidgets.QSpacerItem(20, 163, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_test)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_testBoard = QtWidgets.QTableWidget(self.widget_5)
        self.tableWidget_testBoard.setMinimumSize(QtCore.QSize(0, 250))
        self.tableWidget_testBoard.setObjectName("tableWidget_testBoard")
        self.tableWidget_testBoard.setColumnCount(4)
        self.tableWidget_testBoard.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_testBoard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_testBoard.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_testBoard.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_testBoard.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.tableWidget_testBoard)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_10.addWidget(self.widget_test)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "税务大数据分析v1.0"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">训练区</p></body></html>"))
        self.pushButton_loadSample.setText(_translate("Form", "数据导入"))
        self.pushButton_extractFeature.setText(_translate("Form", "特征提取"))
        self.pushButton_startTrain.setText(_translate("Form", "开始训练"))
        item = self.tableWidget_trainSamples.horizontalHeaderItem(0)
        item.setText(_translate("Form", "案件描述"))
        item = self.tableWidget_trainSamples.horizontalHeaderItem(1)
        item.setText(_translate("Form", "法规意见"))
        item = self.tableWidget_trainFeature.horizontalHeaderItem(0)
        item.setText(_translate("Form", "案件描述"))
        item = self.tableWidget_trainFeature.horizontalHeaderItem(1)
        item.setText(_translate("Form", "法规意见"))
        self.label_3.setText(_translate("Form", "案件数量"))
        self.label_4.setText(_translate("Form", "语料库容量"))
        self.label_5.setText(_translate("Form", "法律数量"))
        self.label_6.setText(_translate("Form", "特征维度"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">测试区</p></body></html>"))
        self.pushButton_loadTestCase.setText(_translate("Form", "数据导入"))
        self.pushButton_startTest.setText(_translate("Form", "开始测试"))
        item = self.tableWidget_testBoard.horizontalHeaderItem(0)
        item.setText(_translate("Form", "案件描述"))
        item = self.tableWidget_testBoard.horizontalHeaderItem(1)
        item.setText(_translate("Form", "实际法规意见"))
        item = self.tableWidget_testBoard.horizontalHeaderItem(2)
        item.setText(_translate("Form", "预测法规意见"))
        item = self.tableWidget_testBoard.horizontalHeaderItem(3)
        item.setText(_translate("Form", "相似度"))

